# Configurazione per velocizzare le build di Tauri

[target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[build]
# Usa tutti i core disponibili per la compilazione
jobs = 8

[registries.crates-io]
protocol = "sparse"
